#!/usr/bin/env python3
"""golden: is the generated Java unchanged? (test/check golden)

    test/check golden                  # the smoke set, diffed against test/golden/
    test/check golden --set cover      # + lean-deriv (complete axiom coverage)
    test/check golden peano lean-map   # exactly these
    test/check golden --update         # show the diff, then accept it

Writes one module test/arend/src/GoldenDump.ard with one `putStrLn` per
program, typechecks it in ONE Arend run (the ~20 s start-up is paid once),
splits the output on the markers and diffs each part against
golden/<program>.java. Runs neither javac nor the programs: a golden file
blessed with a bug still passes here, which is why `run` exists.
"""

import argparse
import difflib
import sys
import time

import common as c

GOLDEN_DIR = c.TEST_DIR / "golden"
DUMP = c.TESTS / "src" / "GoldenDump.ard"

# The smoke set: a set cover of the features visible in generated Java (Fix
# classes, mutual fix, case/fields, BOX, literals, letIn, each Rt axiom family),
# minimized by input size. Three of the four are the cheapest program showing
# their feature, so do not prune by size.
SMOKE = {
    "peano":                    "fix, case, construct; no axioms",
    "peregrine-rocq-oddeven":   "mutual fix + qualified this; Rocq frontend",
    "leanbench-even":           "cheapest mutual fix; Nat/PRIM axioms, int literal, letIn, box",
    "leanbench-list_sum_foldr": "the only cheap source of Lean's Array axioms",
    # Not for coverage: the example shown in the top-level README, kept here
    # so that the file it links to is always the compiler's current output.
    "insertion-sort":           "README showcase: higher-order argument, three fix constants",
}
# The only program reaching Rt.EQ_REC and Rt.INT_*; 23k lines of λ□, ~130 s.
COVER_EXTRA = {
    "lean-deriv": "Eq.rec and the machine-Int axioms",
}
# Not covered by any corpus program: λ□ `proj`, `fvar`, an unguarded `fix` body.

MARKER = r"^===== (\S+) =====$"


def dump_module(selection):
    lines = ["-- GENERATED by test/golden.py -- do not edit.",
             "\\import Data.String", "\\import Debug", "\\import Compiler.ToJava"]
    # `()`: qualified use only; every Imported module exports the same names.
    lines += [f"\\import Imported.{p.module()} ()" for p in selection]
    lines.append("")
    for i, p in enumerate(selection):
        lines.append(f'\\func d{i} => putStrLn ("===== {p.name} =====\\n"'
                     f' ++ compileProgram "Prog" Imported.{p.module()}.program)')
    return "\n".join(lines) + "\n"


def compare(name, produced, update):
    path = GOLDEN_DIR / f"{name}.java"
    if not path.exists():
        if update:
            path.write_text(produced)
            return "new"
        return "no-golden"
    expected = path.read_text()
    if expected == produced:
        return "ok"
    diff = list(difflib.unified_diff(expected.splitlines(True), produced.splitlines(True),
                                     fromfile=f"golden/{name}.java", tofile=f"{name} (now)"))
    print(f"--- {name}: {len(diff)} diff line(s) " + ("(accepting)" if update else "(differs)"))
    sys.stdout.writelines(diff[:400])
    if len(diff) > 400:
        print(f"... {len(diff) - 400} more diff line(s) suppressed")
    if update:
        path.write_text(produced)
        return "updated"
    return "differs"


def main(argv=None):
    p = argparse.ArgumentParser(prog="check golden", description=__doc__.splitlines()[0])
    p.add_argument("programs", nargs="*", metavar="PROGRAM")
    p.add_argument("--set", choices=("smoke", "cover", "all"), default="smoke")
    p.add_argument("--update", action="store_true", help="accept the current output (prints the diff)")
    args = p.parse_args(argv)

    programs = c.load_corpora()
    if args.programs:
        names = args.programs
    elif args.set == "all":
        names = [q.name for q in programs if (GOLDEN_DIR / f"{q.name}.java").exists()]
    else:
        names = list(SMOKE) + (list(COVER_EXTRA) if args.set == "cover" else [])
    selection = [q for q in c.select(programs, names) if c.ensure_imported(q)]
    if not selection:
        c.die("nothing to check")

    start = time.monotonic()
    c.info(f"golden: {len(selection)} program(s), one Arend run")
    DUMP.write_text(dump_module(selection))
    try:
        output = c.arend(c.TESTS, "GoldenDump")
    finally:
        DUMP.unlink(missing_ok=True)
    for line in c.problems(output)[:8]:
        c.warn(line)
    produced = c.sections(output, MARKER)

    statuses = {q.name: compare(q.name, produced[q.name], args.update) if q.name in produced
                else "no-output" for q in selection}
    print()
    for name, status in statuses.items():
        print(f"  {name:28s} {status}")
    bad = [n for n, s in statuses.items() if s in ("differs", "no-output", "no-golden")]
    print(f"\ngolden: {len(statuses)} program(s) in {time.monotonic() - start:.0f}s, "
          f"{len(bad)} failing" + (f": {' '.join(bad)}" if bad else ""))
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
